name: jekyll_app
type: ruby:2.3
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler
    bundle install
    ALGOLIA_API_KEY='56c038bbf2a7d22b11b52a832620c662' bundle exec jekyll algolia
    JEKYLL_ENV=production bundle exec jekyll build
