name: jekyll_app
type: ruby:2.3
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler
    bundle install
    if [ "$PLATFORM_BRANCH" = Master ]; then
    bundle exec jekyll algolia
    fi
    JEKYLL_ENV=production bundle exec jekyll build
